# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank # the website title (if blank, full name will be used instead)
first_name: Can
middle_name: 
last_name: Akin
contact_note: >
  Feel free to reach out through any of these channels.
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  Software engineer passionate about building innovative solutions and exploring cutting-edge technology.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
keywords: software-engineer, developer, portfolio, technology, programming # add your own keywords
lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: 💻 # the emoji used as the favicon (or change to your preferred emoji)

url: https://github.com/akincan01 # CHANGE THIS to your GitHub username
baseurl: # Leave blank for GitHub Pages
last_updated: false # set to true if you want to display last updated in the footer
impressum_path: # set to path to include impressum link in the footer
back_to_top: true # set to false to disable the back to top button

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# repo color theme
repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: false # Disable GitHub trophies for cleaner look
  theme_light: flat
  theme_dark: gitdimmed

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------
# will use title and url fields

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: false # Disable search for cleaner navigation
socials_in_search: false
posts_in_search: false
bib_search: false

# Dimensions
max_width: 930px

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------
serve_og_meta: true # Include Open Graph meta tags for social media sharing
serve_schema_org: true # Include Schema.org for better SEO
og_image: # Add path to your profile image for social media previews

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

google_analytics: # Add your Google Analytics ID if you want tracking
cronitor_analytics: 
pirsch_analytics: 
openpanel_analytics: 

google_site_verification: # Add for Google Search Console
bing_site_verification: 

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: C.AKIN # blog_name will be displayed in your blog page
blog_description: Thoughts on software engineering and technology
permalink: /blog/:year/:title/
lsi: false

# Pagination
pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 3

# Comments - Enable if you want comments on blog posts
giscus:
  repo: # <your-github-username>/<your-github-repo-name>
  repo_id: # leave empty for now
  category: Comments
  category_id: # leave empty for now
  mapping: title
  strict: 1
  reactions_enabled: 1
  input_position: bottom
  theme: preferred_color_scheme
  emit_metadata: 0
  lang: en

# Disable Disqus (deprecated)
disqus_shortname: # leave empty

# External sources - Remove or comment out if not needed
external_sources: []

# -----------------------------------------------------------------------------
# Newsletter
# -----------------------------------------------------------------------------

newsletter:
  enabled: false

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
  projects:
    output: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ["_pages", "_scripts"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - _pages/about_einstein.md
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor
keep_files:
  - CNAME
  - .nojekyll

# Plug-ins
plugins:
  - jekyll-archives-v2
  - jekyll-email-protect
  # - jekyll-feed # Disabled to remove RSS feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-tabs
  - jekyll-terser
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

# Sitemap settings
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed

# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------

jekyll-minifier:
  compress_javascript: false
  exclude: ["robots.txt", "assets/js/search/*.js"]

# -----------------------------------------------------------------------------
# Terser
# -----------------------------------------------------------------------------

terser:
  compress:
    drop_console: true

# -----------------------------------------------------------------------------
# Jekyll Archives
# -----------------------------------------------------------------------------

jekyll-archives:
  posts:
    enabled: [year, tags, categories]
    permalinks:
      year: "/blog/:year/"
      tags: "/blog/:type/:name/"
      categories: "/blog/:type/:name/"

display_tags: ["technology", "programming", "software", "web-development"] # customize with your preferred tags
display_categories: ["projects", "tutorials"] # customize with your categories

# -----------------------------------------------------------------------------
# Jekyll Scholar - Disable since you probably don't need publications
# -----------------------------------------------------------------------------

scholar:
  last_name: [Akin]
  first_name: [Can]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

# Disable publication badges
enable_publication_badges:
  altmetric: false
  dimensions: false
  google_scholar: false
  inspirehep: false

# Filter out publication-related keywords
filtered_bibtex_keywords:
  [
    abbr,
    abstract,
    additional_info,
    altmetric,
    annotation,
    arxiv,
    award,
    award_name,
    bibtex_show,
    blog,
    code,
    google_scholar_id,
    html,
    inspirehep_id,
    pdf,
    poster,
    preview,
    selected,
    slides,
    supp,
    video,
    website,
  ]

max_author_limit: 3
more_authors_animation_delay: 10
enable_publication_thumbnails: false # Disable for cleaner look

# -----------------------------------------------------------------------------
# Jekyll Link Attributes
# -----------------------------------------------------------------------------

external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude:

# -----------------------------------------------------------------------------
# Responsive WebP Images
# -----------------------------------------------------------------------------

imagemagick:
  enabled: false # Keep this for better image performance
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
    - ".gif"
  output_formats:
    webp: "-quality 85"

lazy_loading_images: true

# -----------------------------------------------------------------------------
# Optional Features - Customized for clean portfolio
# -----------------------------------------------------------------------------

enable_google_analytics: false # Set to true and add your GA ID if you want tracking
enable_cronitor_analytics: false
enable_pirsch_analytics: false
enable_openpanel_analytics: false
enable_google_verification: false # Set to true and add verification code for SEO
enable_bing_verification: false
enable_masonry: true # Nice project card arrangement
enable_math: false # Disable unless you write math-heavy content
enable_tooltips: false # Keep clean
enable_darkmode: true # Nice feature to have
enable_navbar_social: true # Show social links in navbar
enable_project_categories: true # Good for organizing projects
enable_medium_zoom: true # Nice image zoom feature
enable_progressbar: true # Shows reading progress
enable_video_embedding: false

# -----------------------------------------------------------------------------
# CV Configuration - Add your CV PDF
# -----------------------------------------------------------------------------

cv_pdf: assets/pdf/cv_can_akin_2025.pdf # Your CV PDF

# -----------------------------------------------------------------------------
# Social Links Configuration
# -----------------------------------------------------------------------------

# Social links
socials:
  email: akin.can2001@gmail.com
  github: akincan01
  linkedin: can-akin-45b305188
  # Disable other social links not needed
  twitter: 
  facebook: 
  instagram: 
  scholar: 
  orcid: 
  github_username: akincan01 # for backward compatibility

# Social network usernames (REQUIRED if above is not set)
linkedin_username: can-akin-45b305188
github_username: akincan01
email: akin.can2001@gmail.com

# -----------------------------------------------------------------------------
# Library versions (keeping the same for compatibility)
# -----------------------------------------------------------------------------

third_party_libraries:
  # ... (keeping all the library configurations the same for stability)
  download: false
  bootstrap-table:
    integrity:
      css: "sha256-uRX+PiRTR4ysKFRCykT8HLuRCub26LgXJZym3Yeom1c="
      js: "sha256-4rppopQE9POKfukn2kEvhJ9Um25Cf6+IDVkARD0xh78="
    url:
      css: "https://cdn.jsdelivr.net/npm/bootstrap-table@{{version}}/dist/bootstrap-table.min.css"
      js: "https://cdn.jsdelivr.net/npm/bootstrap-table@{{version}}/dist/bootstrap-table.min.js"
    version: "1.22.4"
  # ... (rest of libraries remain the same)

# -----------------------------------------------------------------------------
# Get external JSON data
# -----------------------------------------------------------------------------

jekyll_get_json:
  - data: resume
    json: assets/json/resume.json

jsonresume:
  - basics
  - work
  - education
  - projects
  - skills
  - languages
  - interests